version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install awscli
          command: |
            sudo apt -y -qq install awscli
      - run:
          name: Configure awscli
          command: |
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
            aws configure set default.region ${AWS_DEFAULT_REGION}
      - restore_cache:
          keys:
            - v2-{{ .Branch }}
          paths:
            - ~/caches/doc-utils-base.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/caches/doc-utils-base.tar | true
      - run:
          name: Build doc-utils-base Docker image
          command: |
            docker build --cache-from=doc-utils-base -t doc-utils-base doc-utils-base/.
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/doc-utils-base.tar doc-utils-base
      - save_cache:
          key: v2-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/caches/doc-utils-base.tar
      - run:
          name: Build doc-utils-common Docker image
          command: |
            docker build -t doc-utils-common doc-utils-common/.
      - run:
          name: Build doc-utils-imghandler Docker image
          command: |
            docker build -t doc-utils-imghandler doc-utils-imghandler/.
      - run:
          name: Build doc-utils-pdfhandler Docker image
          command: |
            docker build -t doc-utils-pdfhandler doc-utils-pdfhandler/.
#      - run:
#          name: Build doc-utils-pythonlibs Docker image
#          command: |
#            cd doc-utils-pythonlibs && docker build -t doc-utils-pythonlibs . && cd ..
      - run:
          name: download img2lambda
          command: |
            wget https://github.com/awslabs/aws-lambda-container-image-converter/releases/download/0.1.0/linux-amd64-img2lambda
            chmod +x linux-amd64-img2lambda
      - run:
          name: Deploy doc-utils-binaries layer
          command: |
            ./linux-amd64-img2lambda -n docutils-bin -i doc-utils-common:latest -r ap-southeast-2 --cr python3.6 --cr python3.7 --desc "Add on layer for python 3.6 and 3.7 to give extra binaries relevant for document inspection/extraction"
            ./linux-amd64-img2lambda -n docutils-bin -i doc-utils-imghandler:latest -r ap-southeast-2 --cr python3.6 --cr python3.7 --desc "Add on layer for python 3.6 and 3.7 specific to images"
            ./linux-amd64-img2lambda -n docutils-bin -i doc-utils-pdfhandler:latest -r ap-southeast-2 --cr python3.6 --cr python3.7 --desc "Add on layer for python 3.6 and 3.7 specific to PDF's"
#     - store_artifacts:
#          path: output/
#          destination: artifacts
